### ISSUE TITLE
Installer can't find Terminal.app on OS X Big Sur 11.2.1

### ISSUE THREAD

**Issue by yennster** [ARMmbed/mbed-cli-osx-installer#2]
```
​Printing from run-mbed-cli.py
 MBED_CLI_APP_DIR=/Applications/MBEDCLI.app/Contents/Resources
$HOME= /Users/jenny
The application /Applications/Utilities/Terminal.app cannot be opened for an unexpected reason, error=Error Domain=NSCocoaErrorDomain Code=260 "The file “Terminal.app” couldn’t be opened because there is no such file." UserInfo={NSURL=file:///Applications/Utilities/Terminal.app, NSFilePath=/Applications/Utilities/Terminal.app, NSUnderlyingError=0x7f9540e0de10 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
```

**Comment by marcel-bluestone** [comment]
I found that Terminal.app now is located at /System/Applications/Utilities/Terminal.app 

I patched the script file (just search inside the package for /Applications/Utilities/Terminal.app) and changed it to /System/Applications.... and it worked!

**Comment by petertorelli** [comment]
Thanks, that fixed the Terminal.App problem, but there's another. I'm trying to install mbed on a new BigSur mac and hitting problems with miniconda:

```Python
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 110, in main
        from ..activate import main as activator_main
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/conda/activate.py", line 11, in <module>
        from .base.context import ROOT_ENV_NAME, context, locate_prefix_by_name
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/conda/base/context.py", line 18, in <module>
        from .._vendor.auxlib.collection import frozendict
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 7, in <module>
        from .compat import isiterable, iteritems, odict, text_type
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 7, in <module>
        from ._vendor.five import WhateverIO as StringIO, with_metaclass
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
        absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
        func = self.__getitem__(name)
      File "/Applications/MBEDCLI.app/Contents/Resources/miniconda/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

`$ /Applications/MBEDCLI.app/Contents/Resources/miniconda/bin/conda shell.posix activate`
```

easier to just do `python3 -m pip install mbed-cli`...
